begin;
select plan(37);

insert into auth.users(id) values ('81111111-1111-4111-8111-111111111111'), ('82222222-2222-4222-8222-222222222222');
create function pg_temp.merge_batch() returns jsonb language sql as $$
  select '{"protocolVersion":1,"accountId":"81111111-1111-4111-8111-111111111111","runs":[],"history":[],"studyDays":[]}'::jsonb;
$$;
create function pg_temp.merge_run() returns jsonb language sql as $$
  select '{"runId":"a","lessonId":"fictional","lessonVersion":"2026-09-10T00:00:00Z","lessonName":"A","language":"english","level":4,"stage":7,"nextUnit":0,"nextPhrase":0,"activeMs":0,"settings":{"mode":"manual","display":"current","speed":1,"advanceDelayMs":1000,"groupSize":2,"groupGapMs":500,"wpmLevel":3,"speakingExtraMs":500,"lineGapMs":1000,"sectionGapMs":2000},"confirmedCycles":0}'::jsonb;
$$;
set local role authenticated;
set local request.jwt.claims = '{"sub":"81111111-1111-4111-8111-111111111111","role":"authenticated","is_anonymous":false}';
select throws_ok($$insert into public.learner_snapshots(account_id,schema_version,snapshot) values ('81111111-1111-4111-8111-111111111111',1,'{"schemaVersion":1,"accountId":"81111111-1111-4111-8111-111111111111","preferredLevel":1,"settings":{},"runs":[],"history":[],"studyDays":[]}')$$,'42501',null,'legacy direct insert denied');
select throws_ok($$update public.learner_snapshots set snapshot=snapshot$$,'42501',null,'legacy direct update denied');
select lives_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || jsonb_build_object('runs',jsonb_build_array(pg_temp.merge_run() || '{"activeMs":9000,"nextPhrase":1}')))$$,'first merge creates row');
select is((select options_revision from public.learner_snapshots),0::bigint,'new automatic row starts options revision zero');
select lives_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || jsonb_build_object('runs',jsonb_build_array(pg_temp.merge_run() || '{"activeMs":4000,"nextPhrase":8,"nextUnit":4}')))$$,'farther merge accepted');
select is((select snapshot#>'{runs,0}' @> '{"activeMs":9000,"nextPhrase":8,"nextUnit":4}' from public.learner_snapshots),true,'coherent checkpoint with max active time');
select lives_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || jsonb_build_object('runs',jsonb_build_array(jsonb_set(pg_temp.merge_run() || '{"nextPhrase":8,"nextUnit":1}', '{settings,groupSize}', '4'))))$$,'settings tie break accepted');
select is((select snapshot#>'{runs,0,nextUnit}' from public.learner_snapshots),'1'::jsonb,'canonical settings precede group index');
select lives_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || jsonb_build_object('history',jsonb_build_array(pg_temp.merge_run() || '{"completedAt":"2026-09-11T09:00:00+09:00"}')))$$,'completion accepted');
select lives_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || jsonb_build_object('runs',jsonb_build_array(pg_temp.merge_run() || '{"nextPhrase":99}')))$$,'late active retry accepted');
select is((select jsonb_array_length(snapshot->'runs') from public.learner_snapshots),0,'late active cannot resurrect completion');
select is((select snapshot#>>'{history,0,completedAt}' from public.learner_snapshots),'2026-09-11T00:00:00.000Z','completion timestamp normalized');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || '{"token":"fictional"}')$$,'P1001','invalid-merge','unknown top level field denied');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || '{"options":null}')$$,'P1001','invalid-merge','null options rejected with stable code');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || '{"options":[]}')$$,'P1001','invalid-merge','array options rejected with stable code');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || '{"options":{"expectedRevision":0,"preferredLevel":1,"settings":{"unknown":1}}}')$$,'P1001','invalid-merge','partial option settings reject unknown fields');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || '{"runs":null}')$$,'P1001','invalid-merge','null runs rejected');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || '{"studyDays":["2026-02-30"]}')$$,'P1001','invalid-merge','invalid calendar days rejected');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || '{"studyDays":["2026-09-10","2026-09-10"]}')$$,'P1001','invalid-merge','duplicate days within a batch rejected');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || jsonb_build_object('runs',jsonb_build_array(pg_temp.merge_run(),pg_temp.merge_run())))$$,'P1001','invalid-merge','duplicate run IDs within a batch rejected');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || jsonb_build_object('history',jsonb_build_array(pg_temp.merge_run() || '{"completedAt":"2026-09-11T00:00:00Z","extra":true}')))$$,'P1001','invalid-merge','completion fields are exact');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || jsonb_build_object('runs',jsonb_build_array(pg_temp.merge_run() || '{"writer":"fictional"}')))$$,'P1001','invalid-merge','unknown nested run field denied');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || jsonb_build_object('runs',jsonb_build_array(jsonb_set(pg_temp.merge_run(),'{settings,writer}','"fictional"'))))$$,'P1001','invalid-merge','unknown nested settings field denied');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || jsonb_build_object('runs',jsonb_build_array(pg_temp.merge_run() || '{"lessonId":"other"}')))$$,'P1001','invalid-merge','immutable identity conflict rejected');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || '{"protocolVersion":2}')$$,'P1002','client-update-required','unsupported protocol rejected');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || '{"accountId":"82222222-2222-4222-8222-222222222222"}')$$,'P1004','account-changed','foreign account denied at RPC');
select lives_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || '{"options":{"expectedRevision":0,"preferredLevel":7,"settings":{"speed":0.75}}}')$$,'explicit options CAS accepted');
select is((select options_revision from public.learner_snapshots),1::bigint,'options revision incremented once');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || '{"studyDays":["2026-09-11"],"options":{"expectedRevision":0,"preferredLevel":2,"settings":{}}}')$$,'P1003','options-conflict','stale options CAS rejected');
select is((select snapshot#>>'{preferredLevel}' from public.learner_snapshots),'7','CAS conflict preserves options');
select is((select snapshot->'studyDays' from public.learner_snapshots),'[]'::jsonb,'CAS conflict rolls back learning');
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch() || jsonb_build_object('runs', (select jsonb_agg(pg_temp.merge_run() || jsonb_build_object('runId',n::text)) from generate_series(1,2001) n)))$$,'P1005','merge-limit','count limit enforced at RPC');
set local request.jwt.claims = '{"sub":"82222222-2222-4222-8222-222222222222","role":"authenticated","is_anonymous":false}';
select is((select count(*) from public.learner_snapshots),0::bigint,'other owner cannot read data');
set local request.jwt.claims = '{"sub":"81111111-1111-4111-8111-111111111111","role":"authenticated","is_anonymous":true}';
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch())$$,'42501',null,'anonymous authenticated owner denied');
reset role;
update public.learner_snapshots set snapshot = snapshot || '{"unknown":"preserve-me"}' where account_id='81111111-1111-4111-8111-111111111111';
set local role authenticated;
set local request.jwt.claims = '{"sub":"81111111-1111-4111-8111-111111111111","role":"authenticated","is_anonymous":false}';
select throws_ok($$select public.merge_learning_snapshot(pg_temp.merge_batch())$$,'P1001','invalid-merge','malformed stored row rejected');
select is((select snapshot->>'unknown' from public.learner_snapshots),'preserve-me','malformed stored data preserved');
set local role anon;
select throws_ok($$select public.merge_learning_snapshot('{}')$$,'42501',null,'anon lacks RPC execute');
reset role;
select * from finish();
rollback;
